### PR TITLE
upgrading gradle version of the library and the app

### PR DESCRIPTION
**Pull request by MohamedWael**

### CODE REVIEW

**Comment by sparrow007** [comment]
@MohamedWael thanks for your contribution let me review this pr request :)

**Comment by MohamedWael** [comment]
Hello @sparrow007 
Have you reviewed the PR :)

**Comment by sparrow007** [comment]
@MohamedWael Thanks

**Comment by sparrow007** [comment]
@MohamedWael i will update this library on bintray soon.

**Comment by MohamedWael** [comment]
Thanks :)

**Pull request merged**
